from keyword import kwlist

RESERVED_KEYWORKDS = [
    *kwlist,  # reserved for python
    # reserved for C
    "auto",
    "break",
    "case",
    "char",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extern",
    "float",
    "for",
    "goto",
    "if",
    "int",
    "long",
    "register",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "struct",
    "switch",
    "typedef",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
    "_Bool",
    "_Complex",
    "_Imaginary",
    "inline",
    "_Packed",
    # reserved for C++
    "class",
    "delete",
    "false",
    "friend",
    "inline",
    "new",
    "operator",
    "private",
    "protected",
    "public",
    "this",
    "true",
    "virtual",
]


ALLOWED_INTERVALS = [-1, 10, 50, 100, 500, 1000, 5000]
