import os
import re

import jinja2 as j2

from canlib.common import utils
from canlib.common.network import Network
from canlib.generators.sources.schema import BitSet, Enum, Number, Schema

__UTILS_CPP_TEMPLATE_ = os.path.dirname(__file__) + "/network_utils_template.h.j2"
__UTILS_PYTHON_TEMPLATE_ = os.path.dirname(__file__) + "/network_utils_template.py.j2"


def generate_utils(schema: Schema, network: Network, filename, utils_dir_network):
    types, structs, messages = __parse_schema(schema, network)

    with open(f"{utils_dir_network}/cpp/{filename}_utils.h", "w") as f:
        f.write(__generate_cpp_utils(filename, types, structs, messages))
    print(f"Generated {filename}_utils.h into {utils_dir_network}/cpp")

    with open(f"{utils_dir_network}/python/{filename}_utils.py", "w") as f:
        f.write(__generate_python_utils(filename, types, structs, messages))
    print(f"Generated {filename}_utils.py into {utils_dir_network}/python")


def __generate_cpp_utils(filename, types, structs, messages):
    with open(__UTILS_CPP_TEMPLATE_, "r") as f:
        skeleton_py = f.read()

    code = j2.Template(skeleton_py).render(
        filename=filename,
        types=types,
        structs=structs,
        messages=messages,
        utils=utils,
        isinstance=isinstance,
        BitSet=BitSet,
        Enum=Enum,
        Number=Number,
    )

    return code


def __generate_python_utils(filename, types, structs, messages):
    with open(__UTILS_PYTHON_TEMPLATE_, "r") as f:
        skeleton_py = f.read()

    code = j2.Template(skeleton_py).render(
        filename=filename, messages=messages, utils=utils
    )

    return code


def __parse_schema(schema: Schema, network: Network):

    types = schema.types
    structs = schema.structs
    messages = {}
    for message_name, message_contents in network.messages.items():
        if (
            message_contents.get("split_senders", False) == True
        ):  # Check if the message was generated by splitting senders
            message_name = re.sub(
                r"_\d+$", "", message_name
            )  # Use regex to remove _<number> at the end of the name

        if not message_name in messages:
            messages[message_name] = []
            messages[message_name].append(message_contents["id"])
        else:
            messages[message_name].append(message_contents["id"])

    return types, structs, messages
